qawolf:
  image: qawolf/playwright-ci:v0.7.0

  cache:
    paths:
      - node_modules/

  script:
    - npm install
    # Start local server
    - npm run start & npx wait-on http://localhost:3000
    - npx qawolf test --headless --all-browsers

  variables:
    # configure tests with environment variables
    FFMPEG_PATH: /usr/bin/ffmpeg # for recording video
    QAW_ARTIFACT_PATH: $CI_PROJECT_DIR/artifacts

  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/artifacts
    expire_in: 1 week
