qawolf:
  image: qawolf/qawolf@sha256:77f687a3c0d80cb1210b33d4f3945e37f99773a0b93a927a94c987df1cce0b4d

  script:
    - npm install
    - npm run start &
    - npx wait-on http://localhost:3000
    - npx qawolf test

  variables:
    QAW_ARTIFACT_PATH: $CI_PROJECT_DIR/artifacts
    # connect to the node server
    URL: http://localhost:3000

  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/artifacts
    expire_in: 1 week
