language: node_js
dist: bionic
addons:
  apt:
    packages:
      # These are required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
      - libegl1
      - libgles2
      - libevent-2.1-6
      - libnotify4
      - libvpx5
      - libxslt1.1
      # This is required to run chromium
      - libgbm1
      # this is needed for running headful tests
      - xvfb
cache:
  directories:
    - node_modules
env:
  - QAW_ARTIFACT_PATH=artifacts QAW_LOG_LEVEL=debug URL=http://localhost:3000
script:
  - "npm run start &"
  - "npx wait-on http://localhost:3000"
  - "npx qawolf test --all-browsers"
jobs:
  include:
    - node_js: "12"
