pipelines:
  default:
    - step:
        name: Test
        image: qawolf/qawolf:v0.8.2
        caches:
          - node
        script:
          - npm install
          - npm run start & npx wait-on http://localhost:3000
          - QAW_ARTIFACT_PATH=artifacts npx qawolf test
        artifacts:
          - artifacts/**
