pipelines:
  default:
    - step:
        name: QA Wolf Tests
        image: qawolf/playwright-ci:v0.6.0
        caches:
          - node
        script:
          - npm install

          # Start local server
          - npm run start & npx wait-on http://localhost:3000
          - QAW_ARTIFACT_PATH=artifacts npx qawolf test --headless --all-browsers
        artifacts:
          - artifacts/**
