pipelines:
  default:
    - step:
        name: Test
        image: qawolf/qawolf:v0.9.3-alpha.0
        caches:
          - node
        script:
          - npm install
          - npm run start & npx wait-on http://localhost:3000
          - QAW_ARTIFACT_PATH=artifacts npx qawolf test --all-browsers
        artifacts:
          - artifacts/**
