name: qawolf
on:
  push:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - run: npm install

      - run: npm run start & npx wait-on http://localhost:3000

      - run: npx qawolf test
        env:
          QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts
          QAW_LOG_LEVEL: debug
          # connect to the node server
          URL: http://localhost:3000

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: ${{ github.workspace }}/artifacts
