name: qawolf
on:
  push:
    # test every branch
    # edit below if you only want certain branches tested
    branches: "*"
  # schedule:
  #   # test on schedule using cron syntax
  #   - cron: "0 * * * *" # every hour
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: qawolf test
        uses: docker://qawolf/qawolf:v0.7.7
        with:
          args: "qawolf test"
        env:
          # output artifacts
          QAW_DOM_PATH: /github/workspace/artifacts
          QAW_LOG_PATH: /github/workspace/artifacts
          QAW_VIDEO_PATH: /github/workspace/artifacts
        #   # configure tests with environment variables
        #   # https://docs.qawolf.com/docs/configuration
        #   QAW_SLEEP_MS: 0
        #   # you can also use GitHub secrets for environment variables
        #   # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
        #   LOGIN_PASSWORD: ${{ secrets.PASSWORD }}
      - name: Upload Artifacts
        # include test artifacts
        # edit below to only include artifacts in certain scenarios
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: "./artifacts"
    ## use your container in the workflow
    # services:
    #   my_service:
    #     image: owner/image:tag
