name: qawolf
on:
  push:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - name: Start local server
        run: npm run start & npx wait-on http://localhost:3000

      - run: npx qawolf test
        env:
          QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts
          URL: http://localhost:3000

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: ${{ github.workspace }}/artifacts
