name: qawolf
on:
  push:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
      - run: npm install
      - name: Start node server
        run: npm run start & npx wait-on http://localhost:3000
      - name: qawolf test
        uses: docker://qawolf/qawolf:v0.7.11
        with:
          args: "qawolf test"
        env:
          # output artifacts
          QAW_DOM_PATH: /github/workspace/artifacts
          QAW_LOG_PATH: /github/workspace/artifacts
          QAW_VIDEO_PATH: /github/workspace/artifacts
          # connect to the node server
          URL: http://docker-host:3000
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: "./artifacts"
